- .github/workflows/CD.yml
- src/main/java/com/server/bbo_gak/global/config/WebConfig.java
- src/main/java/com/server/bbo_gak/global/config/security/SecurityConfig.java
- src/main/resources/static/docs/open-api-3.0.1.json
- close # 20
- RestDocs의 swagger 변환이 CD시 적용이 안되는 것 해결
- ./gradlew clean build로 변경 
- 
-
> [chore][#20]CI/CD 명령어 변경 및 cors ip 추가

- src/main/java/com/server/bbo_gak/domain/card/entity/Card.java
- src/main/java/com/server/bbo_gak/domain/card/entity/CardMemo.java
- src/main/java/com/server/bbo_gak/domain/card/entity/CardType.java
- src/main/java/com/server/bbo_gak/domain/card/entity/CopyInfo.java
- src/main/java/com/server/bbo_gak/domain/card/service/CardMemoService.java
- src/main/java/com/server/bbo_gak/domain/recruit/entity/Recruit.java
- src/main/java/com/server/bbo_gak/domain/recruit/entity/RecruitSchedule.java
- src/main/java/com/server/bbo_gak/domain/recruit/entity/RecruitStage.java
- src/main/java/com/server/bbo_gak/domain/recruit/entity/RecruitStatus.java
- src/main/java/com/server/bbo_gak/domain/recruit/service/RecruitScheduleService.java
- src/main/java/com/server/bbo_gak/domain/recruit/service/RecruitService.java
- src/main/resources/static/docs/open-api-3.0.1.json
- src/test/resources/card-test-data.sql
> Feature/#24 2차 MVP 인터페이스 설계

- src/main/java/com/server/bbo_gak/domain/card/controller/CardImageController.java
- src/main/java/com/server/bbo_gak/domain/card/dto/request/CardImageUploadCompleteRequest.java
- src/main/java/com/server/bbo_gak/domain/card/service/CardImageService.java
- src/main/java/com/server/bbo_gak/domain/card/service/CardImageServiceImpl.java
- src/main/resources/static/docs/open-api-3.0.1.json
- src/test/java/com/server/bbo_gak/domain/Image/controller/ImageControllerTest.java
- src/test/java/com/server/bbo_gak/domain/auth/controller/AuthControllerTest.java
- src/test/java/com/server/bbo_gak/domain/card/controller/CardImageControllerTest.java
- src/test/java/com/server/bbo_gak/domain/card/service/CardImageServiceImplTest.java
- src/test/java/com/server/bbo_gak/global/RestDocsFactory.java
- close # 27
- RestDocsFactory 를 통한 API 문서 작성 생산성을 향상 시켰습니다.
- 
-
> Feature/#27 RestDocsFactory 를 통한 API 문서 작성 생산성 향상

- src/main/java/com/server/bbo_gak/global/config/WebConfig.java
- src/main/java/com/server/bbo_gak/global/config/security/SecurityConfig.java
> [chore][#34]localhost:3000 추가

- src/main/java/com/server/bbo_gak/domain/card/controller/CardMemoController.java
- src/test/java/com/server/bbo_gak/domain/card/controller/CardMemoControllerTest.java
- src/test/resources/card-test-data.sql
- #36
- 카드 메모 api test 코드 작성
- restdocs req, res null 인 경우 수정 반영되면 팩토리 사용하는 틀로 바꿀 예정, 카드 api 테스트 코드도!
- na
> [test][#36] 카드 메모 api 테스트 코드 작성

- src/main/java/com/server/bbo_gak/domain/auth/controller/AuthController.java
> [fix][#39] merge 오류

- src/main/java/com/server/bbo_gak/domain/card/entity/Card.java
- src/main/java/com/server/bbo_gak/domain/recruit/entity/Recruit.java
- src/main/java/com/server/bbo_gak/domain/recruit/service/RecruitService.java
- src/main/java/com/server/bbo_gak/global/error/GlobalExceptionHandler.java
- src/main/resources/application-dev.yml
- src/main/resources/application.yml
- src/test/java/com/server/bbo_gak/domain/recruit/controller/RecruitControllerTest.java
- src/test/resources/application-test.yml
- src/test/resources/recruit-test-data.sql
> [feat][#64] deadLine nullable & recruit 삭제 에러 수정

- src/main/java/com/server/bbo_gak/global/config/WebConfig.java
- src/main/resources/application.yml
> [hotfix] swagger 안됨 에러 중지

- src/main/java/com/server/bbo_gak/domain/recruit/controller/RecruitController.java
- src/main/java/com/server/bbo_gak/domain/recruit/dto/response/RecruitGetInnerResponse.java
- src/main/java/com/server/bbo_gak/domain/recruit/service/RecruitService.java
- src/test/java/com/server/bbo_gak/domain/recruit/controller/RecruitControllerTest.java
> [feat][#72] 공고 조회 누락 해결

- build.gradle
- src/main/java/com/server/bbo_gak/global/config/sentry/SentryConfig.java
- src/main/resources/application.yml
- src/test/resources/application-test.yml
> [feat][#74] Sentry 적용 완료

- src/main/java/com/server/bbo_gak/domain/card/entity/CardCopyInfo.java
- src/main/java/com/server/bbo_gak/domain/card/entity/CardImage.java
- src/main/java/com/server/bbo_gak/domain/card/entity/CardMemo.java
- src/main/java/com/server/bbo_gak/domain/card/entity/CardTag.java
- src/main/java/com/server/bbo_gak/domain/card/entity/CardType.java
- src/main/java/com/server/bbo_gak/domain/card/entity/Tag.java
- src/main/java/com/server/bbo_gak/domain/notification/entity/Notification.java
- src/main/java/com/server/bbo_gak/domain/recruit/entity/RecruitSchedule.java
- src/main/java/com/server/bbo_gak/domain/recruit/entity/Season.java
- src/main/java/com/server/bbo_gak/domain/user/entity/User.java
- src/test/resources/card-test-data.sql
- src/test/resources/notification-test-data.sql
- src/test/resources/recruit-test-data.sql
- src/test/resources/season-test-data.sql
- close #75
- soft delete
- n/a
- n/a
> [feat][#75] 모든 테이블 soft delete 추가 & 테스트 데이터 수정

- .github/workflows/CD.yml
- docker-compose-dev.yml
- nginx/Dockerfile
- nginx/nginx.conf
- src/main/java/com/server/bbo_gak/global/config/WebConfig.java
- close #80 
- docker-compose-dev에 niginx와 ssl 인증을 위한 certbot 컨테이너를 추가했습니다.
- cors를 위해 "https://www.bbogak.com/", "https://dev.bbogak.com/"를 추가했습니다
- 
-
> [feat][#80] nginx 설정 및 ssl 설정

- .github/workflows/CD.yml
- src/main/java/com/server/bbo_gak/global/config/security/SecurityConfig.java
> [feat][#80] cors 설정 다시

- build.gradle
> [feat][#80] swagger build ip 변경

- .github/workflows/CD.yml
> [feat][#80] cd 변경

- src/main/java/com/server/bbo_gak/domain/card/controller/CardInRecruitController.java
- src/main/java/com/server/bbo_gak/domain/card/dao/CardCopyInfoRepository.java
- src/main/java/com/server/bbo_gak/domain/card/dto/request/CopyCardFromMyInfoRequest.java
- src/main/java/com/server/bbo_gak/domain/card/service/CardInRecruitService.java
- src/main/java/com/server/bbo_gak/domain/card/service/CardService.java
- src/main/java/com/server/bbo_gak/domain/card/service/CardTypeService.java
- src/test/java/com/server/bbo_gak/domain/card/controller/CardInRecruitControllerTest.java
- close #88 
- 카드 공고로 복사시 카드 타입 조건 생성 로직 수정
- na
- na
> [feat][#88] 카드 공고로 복사시 카드 타입 조건 생성 로직 수정

- src/main/java/com/server/bbo_gak/domain/recruit/service/RecruitService.java
> [fix][#98] 스케줄 추가 안됨 해결

- src/main/java/com/server/bbo_gak/domain/card/dto/response/CardGetResponse.java
- src/test/java/com/server/bbo_gak/domain/card/controller/CardControllerTest.java
- close #95 
- 카드 단건 조회시 생성 시간 포함
- na
- na
> [feat][#95] 카드 단건 조회시 생성 시간 포함

- src/main/java/com/server/bbo_gak/domain/card/dao/TagRepository.java
- src/main/java/com/server/bbo_gak/domain/card/service/TagService.java
- close #95 
- 인성 태그 조회 조건 추가
- 
-
> [feat][#95] 인성 태그 조회 조건 추가

- src/main/java/com/server/bbo_gak/domain/recruit/dto/request/RecruitCreateRequest.java
- src/main/java/com/server/bbo_gak/domain/recruit/entity/RecruitStatus.java
- src/main/java/com/server/bbo_gak/domain/recruit/entity/RecruitStatusCategory.java
- src/main/java/com/server/bbo_gak/domain/recruit/service/RecruitService.java
> Feature/#98 공고관련 이슈 해결

- src/main/java/com/server/bbo_gak/domain/card/controller/TagController.java
- src/main/java/com/server/bbo_gak/domain/card/dto/response/CardGetResponse.java
- src/main/java/com/server/bbo_gak/domain/card/service/TagService.java
- src/test/java/com/server/bbo_gak/domain/card/controller/CardControllerTest.java
- src/test/java/com/server/bbo_gak/domain/card/controller/TagControllerTest.java
- close #104
- 공고에서 태그 조회시 생성된 태그만 보이게끔
- na
- na
> [feat][#104] 공고에서 태그 조회시 생성된 태그만 보이게끔

- src/main/java/com/server/bbo_gak/domain/card/controller/TagController.java
- src/main/java/com/server/bbo_gak/domain/card/service/TagService.java
- src/main/java/com/server/bbo_gak/global/error/exception/ErrorCode.java
- src/test/java/com/server/bbo_gak/domain/card/controller/TagControllerTest.java
- close #95 
- 태그 조회 버그 수정
- na
- na
> [feat][#95] 공고에서 태그 조회시 생성된 태그만 보이게끔

- src/main/java/com/server/bbo_gak/domain/recruit/dao/RecruitRepository.java
- src/main/java/com/server/bbo_gak/domain/recruit/service/RecruitService.java
> [fix][#94]최신순 버그 픽스

- build.gradle
> 프로필별 swagger url 변경

- src/main/java/com/server/bbo_gak/global/error/exception/ErrorCode.java
> 카드 메모 에러 메세지 오류

- build.gradle
- src/main/resources/logback-spring.xml
> [feat][#9] logback 추가

- src/main/java/com/server/bbo_gak/domain/card/dto/response/CardGetResponse.java
- src/main/java/com/server/bbo_gak/domain/card/dto/response/TagGetResponse.java
- src/test/java/com/server/bbo_gak/domain/card/controller/CardControllerTest.java
- src/test/java/com/server/bbo_gak/global/RestDocsFactory.java
- close #120 
- 이제 DTO에 list를 넣어도 RestDocsFactory 클래스의 함수를 사용할 수 있습니다.
- 
-
> [feat][#120] list도 추가

- src/main/java/com/server/bbo_gak/domain/card/controller/CardSearchController.java
- src/main/java/com/server/bbo_gak/domain/card/dao/CardDao.java
- src/main/java/com/server/bbo_gak/domain/card/dao/CardTagSearchHistoryRepository.java
- src/main/java/com/server/bbo_gak/domain/card/service/CardSearchService.java
- src/test/java/com/server/bbo_gak/domain/card/controller/CardSearchControllerTest.java
- src/test/resources/card-test-data.sql
- close #117 
- 검색 api 수정 
- n/a
-  n/a
> [hotfix][#117] card search api 변경
